-- Retail Store Database Analysis
-- Author: Vaibhav Deshmukh
-- Purpose: To track inventory and calculate monthly sales

-- 1. Create the Table
CREATE TABLE Sales (
    SaleID INT PRIMARY KEY,
    ProductName VARCHAR(50),
    Category VARCHAR(50),
    Quantity INT,
    PricePerUnit DECIMAL(10, 2),
    SaleDate DATE
);

-- 2. Insert Mock Data (Sample Transactions)
INSERT INTO Sales VALUES (1, 'Laptop', 'Electronics', 1, 55000.00, '2024-01-10');
INSERT INTO Sales VALUES (2, 'Mouse', 'Accessories', 5, 500.00, '2024-01-12');
INSERT INTO Sales VALUES (3, 'T-Shirt', 'Clothing', 10, 800.00, '2024-01-15');
INSERT INTO Sales VALUES (4, 'Phone', 'Electronics', 2, 25000.00, '2024-02-01');
INSERT INTO Sales VALUES (5, 'Jeans', 'Clothing', 3, 1200.00, '2024-02-05');

-- 3. DATA ANALYSIS QUERIES --

-- Q1: What is the Total Revenue generated by the store?
SELECT SUM(Quantity * PricePerUnit) AS Total_Revenue 
FROM Sales;

-- Q2: Which Category sells the most items?
SELECT Category, SUM(Quantity) AS Total_Items_Sold
FROM Sales
GROUP BY Category
ORDER BY Total_Items_Sold DESC;

-- Q3: Find all transactions where the sale amount was greater than 10,000
SELECT ProductName, (Quantity * PricePerUnit) AS Bill_Amount
FROM Sales
WHERE (Quantity * PricePerUnit) > 10000;
